### PR TITLE
CORE-1869: Remove /api/v1/communities mapping

### PR DESCRIPTION
**Pull request by kare**
Waiting for https://github.com/streamr-dev/streamr-client-javascript/pull/122
and maybe others?!

### CODE REVIEW

**Comment by hpihkala** [comment]
Let's hold this back until no calls are being made to the old routes anymore.

**Comment by kare** [comment]
`grep /communities/ /var/log/nginx/streamr_api_access.log |wc -l`

**Comment by kare** [comment]
61618

**Comment by hpihkala** [comment]
How many IP addresses are the requests coming from? If it's just one or two, maybe it's some old script of ours that needs updating and we can identify where it's coming from.

**Comment by kare** [comment]
@hpihkala

```
# grep /communities/ /var/log/nginx/streamr_api_access.log.1 | wc -l
115771
# grep /communities/ /var/log/nginx/streamr_api_access.log.1 | cut -d ' ' -f 1 | uniq | wc -l
115617
```

**Comment by hpihkala** [comment]
Ok, probably Swash is calling the old paths still. Not safe to remove yet - let's recheck after the DU 2.0 upgrade!

**Comment by kare** [comment]
I wonder why new GitHub Actions aren't picked up by this branch after merge?

**Pull request closed without merging**
