### PR TITLE
Expose autoConfigure and storageDays variables on streams

### PR DESCRIPTION
**Pull request by hpihkala**

### CODE REVIEW

**Comment by hpihkala** [comment]
Noticed the ticket and had the relevant stuff open, so just threw this change in quickly. 

@fonty1 are these variables needed in the stream list view? Looks like there's a `stream.getSummaryMap()` method which gets called instead of `stream.getMap()` when calling the stream list endpoint with a query param `noConfig`. For now I didn't add the variables to the "summary map".

**Comment by fonty1** [comment]
> @fonty1 are these variables needed in the stream list view?

@hpihkala pretty fast! No, not needed on the stream list view, only the Stream Details page.

**Comment by fonty1** [comment]
@hpihkala @kare I'm having trouble getting these values to persist on save - can you double check things are OK on your side? 

Below is the curl of the PUT to /streams/ID containing:
"autoConfigure":false,
"requireSignedData":true

but the response I get back ignores these and keeps them as they were. 

Request:
Screenshot 2019-04-10 at 14 18 02

Updated stream:
Screenshot 2019-04-10 at 14 35 04

```
curl 'http://localhost/streamr-core/api/v1/streams/M3F5JFuRTdOJWuwUC3rq5w' -X PUT -H 'Pragma: no-cache' -H 'Origin: http://localhost' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-GB,en;q=0.9,en-US;q=0.8,de;q=0.7,et;q=0.6,fi;q=0.5' -H 'Authorization: Bearer abcd' -H 'Content-Type: application/json' -H 'Accept: application/json, text/plain, */*' -H 'Cache-Control: no-cache' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36' -H 'Cookie: JSESSIONID=984284AB949389C27112D8F1BE0FD4E5; __tawkuuid=e::localhost::PKPtruorse/ztSznixHqEoyHUnqyXda1XFsKKrW5GQgLaQ0dAW6zku1BMs5/9U0A::2; TawkConnectionTime=0' -H 'Connection: keep-alive' -H 'Referer: http://localhost/u/stream/show/M3F5JFuRTdOJWuwUC3rq5w' -H 'DNT: 1' --data-binary '{"id":"M3F5JFuRTdOJWuwUC3rq5w","name":"test","description":"test","config":{"fields":[]},"ownPermissions":[],"lastUpdated":"2019-04-09T16:13:41Z","autoConfigure":false,"partitions":1,"requireSignedData":true,"storageDays":365,"uiChannel":false}' --compressed
```

**Comment by fonty1** [comment]
resolved in: https://github.com/streamr-dev/engine-and-editor/pull/588

**Pull request merged**
