### PR TITLE
WIP: Fix RunCanvasSpec

### PR DESCRIPTION
**Pull request by hpihkala**
Bring back `RunCanvasSpec`, which was originally `@Ignore`d by @harbu months ago due to troubles on Travis.

Two bugs were found and fixed:
- `RunCanvasSpec` was transactional and ended up blocking database transactions executed by the system under test
- Kafka didn't work due to the equivalent of `streamr-docker-dev bind-ip` missing from Travis config

### CODE REVIEW

**Comment by harbu** [comment]
It seems to be broken in local dev environment too. If I start up a new Docker environment from scratch and then proceed to run this test, on the first run it will fail. Subsequent runs pass.

**Comment by hpihkala** [comment]
Compared logs between healthy and unhealthy runs.

Unhealthy:

- Runner thread gets stuck (no further logging for 30 seconds after below line)
`2018-12-20 12:58:50,474 [lettuce-nioEventLoop-4-1] INFO  redis.RedisMessageSource  - Subscribed run-canvas-spec-0 on host 127.0.0.1`
- `SignalPathRunner.waitRunning()` times out after 30 seconds
- Canvas start gets aborted due to timeout

**Clearly the runner thread blocks waiting for something, but I haven't yet found out what.**

Healthy:

- Message that the realtime queue starts right after the subscribe message

```
2018-12-20 12:41:10,327 [lettuce-nioEventLoop-4-1] INFO  redis.RedisMessageSource  - Subscribed run-canvas-spec-0 on host 127.0.0.1
2018-12-20 12:41:10,395 [SignalPathRunner [run-canvas-spec]] INFO  data.RealtimeEventQueue  - The realtime event queue is starting!
```

**Comment by hpihkala** [comment]
@harbu Do you also get those Kafka errors when the test fails locally? (Would be good to establish whether the two symptoms are related)

**Comment by harbu** [comment]
I was only looking at E&E logs but I didn't see any Kafka-related errors? Are they supposed to pop in E&E, Kafka, or ZooKeeper logs?

**Comment by hpihkala** [comment]
Good news: 
- Managed to fix the Kafka errors by adding the `bind-ip` equivalent to the travis script. 
- The test now terminates instead of running until Travis kills it.
Bad news:
- The test still fails with the same symptoms as before.

**Comment by hpihkala** [comment]
The issue was caused by `RunCanvasSpec` being transactional by default. The transaction that wraps the test was blocking other transactions executed in the `SignalPathRunner` thread. Fixed by setting the spec to `transactional = false`.

**Pull request merged**
